### ISSUE TITLE
소드락에서 도는 서비스들 *.sodrak.upnl.org 로 접근 가능하게 만들기

### ISSUE THREAD

**Issue by simnalamburt** [upnl/work#15]

**Comment by jc-kim** [comment]
복구 완료:
http://wiki.sodrak.upnl.org
http://old.wiki.sodrak.upnl.org
http://book.sodrak.upnl.org
http://zal.sodrak.upnl.org
http://trac.sodrak.upnl.org (Internal Server Error)
http://pdns.sodrak.upnl.org (뭐하는 사이트지)
403:
http://menu.sodrak.upnl.org
http://stats.sodrak.upnl.org

이 정도면 대충 접근 가능한 데는 다 고친 듯?

**Comment by simnalamburt** [comment]
Thanks @jc-kim !
