### ISSUE TITLE
[RFC] upnl-snu.slack.com과 UPnL IRC 잇기

### ISSUE THREAD

**Issue by simnalamburt** [upnl/work#36]
upnl-snu.slack.com의 #random 채널을 IRC에 이으면 그것이 가장 적당해보인다.

이을까요? @pbzweihander

**Comment by pbzweihander** [comment]
원래 이으려고 했습니다! 잇는 방법이 있다고만 들어서 구체적으로는 모르지만, 이을 수 있다면 빨리 잇는게 좋을 것 같네요.

**Comment by simnalamburt** [comment]
https://github.com/erikdesjardins/slack-irc-rust 이거 검토중이에여
