### ISSUE TITLE
유리엘 파워 팬이 돌지 않음

### ISSUE THREAD

**Issue by tirr-c** [upnl/work#39]
https://upnl-snu.slack.com/archives/CCA7QKT32/p1537175361000100

올 것이 왔습니다... 파워를 교체해야 합니다. 하는 김에 케이스도 교체합시다.

**Comment by simnalamburt** [comment]
오우 쒯

**Comment by simnalamburt** [comment]
넬방이 먼지가 많아서 유리엘 내부 먼지로 뒤덮여있을것같네요. 내부청소한지 꽤 됐어요. 파워가 멈춘 원인도 먼지때문일것같네요. 이경우 먼지만 청소하면 다시 잘 돌수도있으니까 참고해주세요. 예전에 제가 클라이언트 컴퓨터였던 제미니 뜯어서 서버로 만들때에도 싹 분해해서 청소했었는데, 그때도 안쪽이 엄청 더러웠었어요.

그리고 케이스 새로 산다면, 다음에 케이스 조립할때, 컴퓨터 좀 아시는분이 조립하셔서 컴퓨터 내부 양압상태로 만들어서 먼지 안쌓이게 만들면 좋을텐데, 이거 할줄 아시는 분이 계실까요?

**Comment by simnalamburt** [comment]
버리는것으로 결정됨
