### ISSUE TITLE
소드락 Caddy가 인증서 갱신에 실패하고있음

### ISSUE THREAD

**Issue by simnalamburt** [upnl/work#43]
소드락은 와일드카드 인증서가 필요해서 클라우드플레어 액세스키를 환경변수로 넣게 되어있는데, 뭔진 잘 모르겠지만 얼마전부터 로그인에 실패해서 소드락쪽 웹페이지는 인증서가 전부 만료되었다.

고치자

**Comment by simnalamburt** [comment]
누군가가 caddy 바이너리를 업데이트했는데 이때 cloudflare 플러그인을 켜지 않은것이 문제이다

**Comment by simnalamburt** [comment]
이런 실수를 막기위해 Caddyfile 리포 리드미에 caddy 설치메뉴얼을 적겠음

**Comment by simnalamburt** [comment]
클라우드플레어에 upnl.chairman@gmail.com 으로 로그인해서 API 키를 확인해야하는데, 클라우드플레어 계정에 MFA가 걸려있어서 확인 불가. @pbzweihander 님께서 해주셔야할 것 같네요

일단 수동으로 인증서 갱신하겠음

**Comment by pbzweihander** [comment]
`/etc/init/caddy.conf`에 API Key 추가하고 caddy 재시작했습니다.

**Comment by simnalamburt** [comment]
Great!
