### ISSUE TITLE
홈페이지에 헬스체크 붙이기

### ISSUE THREAD

**Issue by simnalamburt** [upnl/work#45]
이제 유피넬 홈페이지가 도커 스웜을 쓰므로, 헬스체크만 붙여주면 서버에 문제가 생길 시 자동으로 재부팅되게 할 수 있다.

###### References
- https://docs.docker.com/engine/reference/builder/#healthcheck
- https://github.com/femiwiki/parsoid/blob/1db0150945d9d8d84e0d1b8f767916940ed7ea20/Dockerfile#L8

**Comment by pbzweihander** [comment]
홈페이지 Dockerfile에 다음을 추가하였습니다.

```Dockerfile
RUN apk add --no-cache curl
HEALTHCHECK --interval=30s --timeout=3s --start-period=5s \
    CMD curl -f -H "Host: $SERVER_NAME" http://localhost:54321/ || exit 1
```

**Comment by simnalamburt** [comment]
@pbzweihander 닫으면 되나유? 배포하고 실적용 된거죠?

**Comment by pbzweihander** [comment]
상태를 지켜보니 잘 동작하는 것 같습니다. 실제로 뭔가 문제가 생겨 500 에러를 뱉었을 때 자동으로 재시작 되는 것을 확인했습니다.
근데 지금 홈페이지 root (http://upnl.org/)에 GET을 날리는 거라 돌아오는 값이 홈페이지 메인 전체라서 inspect를 통해 봤을 때 로그가 굉장히 더러워 지는 문제가 있습니다.

홈페이지 코드를 수정해서 간단하게 빈 200 OK를 내놓은 endpoint를 추가하고 그걸로 healthcheck를 하도록 바꾼 후 닫겠습니다.

**Comment by pbzweihander** [comment]
`/_healthcheck` endpoint를 만들어 헬스체크를 수행하도록 업데이트했습니다. 잘 작동합니다!
