### ISSUE TITLE
유피넬 페이팔 계정 만들기

### ISSUE THREAD

**Issue by simnalamburt** [upnl/work#47]
https://blog.toss.im/2018/10/18/toss/tips/joint-account/

이거 하면 장점이

- **유피넬 회원 전원이 아무때나 계좌 이체내역을 확인할 수 있어서 자금운용이 매우 투명해짐**
- 회계 바뀔때마다 매번 계좌만들지 않아도 돼서 좋고
- 매번 계좌만들때마다 이체한도 늘리는 번거로움이 줄고
- 유피넬 계좌가 바뀌지 않으니 외부에서 후원금 받거나 회비내거나 이런저런 일 할 때 혼란이 줄고
- 온라인결제 필요할 때 (#31 이라던가) 페이팔계정에 한번 붙여놓고 바꿀 필요가 없음
- 회비독촉기능이 달려있어서 회계가 회원들에게 회비독촉하기 편함
- 계좌가 바뀌지 않으니 계좌에 이체내역이 살아있어 동아리 자금 추적이 쉬워짐

단점은

- 유피넬 회계가 토스를 써야함 (동아리 회비용 계좌 따로 파는것보단 토스계정 생성이 더 쉬울것같지만)

**Comment by pbzweihander** [comment]
토스 공동계좌가 좋아보이긴 하는데, 한도가 150만원인건 너무 작은거 같아 보입니다.

**Comment by simnalamburt** [comment]
http://blog.kakaobank.com/223 카카오뱅크 모임통장이라고 비슷한 상품이 하나 더 있는데 이건 어떤가요?

**Comment by pbzweihander** [comment]
https://www.kakaobank.com/products/moim 카카오톡에 너무 dependent한거 같긴 한데 괜찮아보입니다. 정기모임때 정회원과 회계와 논의해서 사용을 결정해보겠습니다.

**Comment by pbzweihander** [comment]
카카오뱅크 모임 통장도 결국 기존 통장 처럼 예금주가 한명으로 정해져 있는 시스템이라는데, 이러면 회계가 바뀌는 상황에선 여전히 쓰기 힘들어 보입니다.

**Comment by simnalamburt** [comment]
이 문제 다른 해결방안 없을까요

**Comment by pbzweihander** [comment]
바쿠스는 깃헙이나 클라우드플레어 등의 결제정보를 바쿠스의 명의의 페이팔 계정으로 설정해놓고 회계가 바뀌면 페이팔 계정의 결제정보만 바꾸는 식으로 운영한다고 합니다.

정기모임때 비영리단체를 만들자는 의견도 나왔는데 조금 찾아본 결과 힘들거 같다고 하고, 저희도 페이팔 계정을 만드는게 가장 현실적인 해결책일거 같아요..

**Comment by simnalamburt** [comment]
좋아요 그렇게 해주세요

**Comment by simnalamburt** [comment]
혹시 페이팔 계정 만드는데에 어떤 문제가 있다면 알려주세요 도와드릴게요. 3월 21일이 도메인 만료일이어서 그 전에 도메인 이전을 해야하는데, 도메인 이전과정이 통상 적어도 2주는 소요됩니다. 시간이 별로 많이 남지 않았으니 최대한 빨리 진행해야해요.

**Comment by pbzweihander** [comment]
뉴-회계님의 계좌 개설과 카드 발급이 늦어져서 조금 걸릴 것 같습니다. 그래도 1월 안까진 될 것 같네요. 페이팔에 '계좌'를 등록하려면 페이팔 계정 명이 계좌 예금주와 동일해야해서 '카드'를 등록하는 방향으로 가려고 합니다.

**Comment by pbzweihander** [comment]
네오-회계님의 도움으로 페이팔 계정을 개설하고 회계 카드를 등록하고 클라우드플레어 계정과 연결시켰습니다. 이제 도메인 이전 작업을 시작할 수 있습니다.
