### ISSUE TITLE
깃랩을 AWS로 이전하기

### ISSUE THREAD

**Issue by pbzweihander** [upnl/work#57]
#50 에서 제미니에 떠있는 서비스를 AWS 서버로 옮기는 도중, 깃랩 이전 도중에 문제가 생겨 이전되지 않은 상황이라, 이를 따로 이슈로 만들어 트래킹합니다.

**Comment by pbzweihander** [comment]
현재 새 AWS 서버 (에보니)에서는 각 서비스의 PV마다 EBS 볼륨을 하나씩 만드는 방식으로 운용하고 있습니다. EBS는 크기에 비례해서 IO크레딧이 오르는데, 이렇게 하면 EBS 하나하나의 크기가 너무 작아서  IO크레딧이 생성되는 속도보다 IO크레딧을 사용하는 속도가 더 커지게 됩니다. 그래서 저번에 깃랩이 IO 크레딧을 전부 소모하는 장애가 일어났습니다.

위를 해결하기 위해, https://kubernetes.io/blog/2019/04/04/kubernetes-1.14-local-persistent-volumes-ga/ 이걸 이용해서 도커 스웜에서 하듯이 모든 PVC들을 `/srv/git.upnl.org`, `/srv/upnl.org` 등의 폴더에 마운트를 시키고, 이 `/srv` 폴더만 EBS로 마운트합니다. 이렇게 하면 PV들이 안전하게 보존되면서, 큰 하나의 EBS로 뭉치니까 IO 크레딧이 충분할 것 같습니다.

**Comment by pbzweihander** [comment]
위 작업이 너무 힘들고, 깃랩의 이전이 급하다면, 일단 별개의 인스턴스를 띄운 후 거기에서 깃랩을 돌리는 방식으로 할 수도 있습니다.

**Comment by integraldx** [comment]
- [x] infra 리포에 EBS 마운트 정의 추가
- [x] StorageClass 정의
- [x] GitLab 포드 디플로이
- [x] 기존 서비스 LocalStorage 방식으로 변경
- [x] 기존 서비스 데이터 이전
- [x] GitLab 데이터 이전

**Comment by tirr-c** [comment]
깃랩 혼자 2GB를 잡아먹어 t3a.medium으로 커버가 안 되는 수준입니다.

**Comment by tirr-c** [comment]
프로메테우스 끄고 메모리 리밋을 줘도 힘들어하면서 결국엔 죽어 버렸습니다.

```
[ec2-user@ip-172-31-40-14 ~]$ free -h
              total        used        free      shared  buff/cache   available
Mem:           3.8G        1.6G        1.4G         30M        739M        1.9G
Swap:            0B          0B          0B
```

깃랩이 없을 때의 메모리 사용량인데, 최소 요구사항인 2GB가 들어갈 여유가 거의 없습니다. 깃랩까지 제대로 돌리려면 t3a.large가 필요할 것 같습니다.

**Comment by tirr-c** [comment]
t3a.large로 올리고 안정된 것 확인했습니다.

**Comment by simnalamburt** [comment]
@integraldx @pbzweihander @tirr-c 세분 모두 너무 고생 많으셨습니다.
