### ISSUE TITLE
서버들 포트 학외개방 하기

### ISSUE THREAD

**Issue by simnalamburt** [upnl/work#6]
중전과 열심히 연락하면 할 수 있을것같음

**Comment by simnalamburt** [comment]
@vbchunguk 혹시 제가 소드락과 에델브로이 두 서버 80번 포트 학외개방 했을 때처럼, 유리엘도 열어 주실 수 있으신가요? CC되어있었으니  행정실의 ㅈ모 선생님과 그때 했던 논의를 다시한번 하면 될 것같아요.

이 Org에 초대해드렸으니 받아주세용

**Comment by tirr-c** [comment]
포트 개방 요청 메일을 보냈습니다.

**Comment by simnalamburt** [comment]
@VBChunguk 저와 넬장 부넬장에게 CC를 걸어주세요.

**Comment by tirr-c** [comment]
앋 이번 메일은 upnl.chairman에는 CC를 걸었어요

**Comment by simnalamburt** [comment]
이미 보내신 메일 포워드도 부탁드려염

**Comment by tirr-c** [comment]
부넬장도 공식 메일 주소가 있나요?

**Comment by simnalamburt** [comment]
아녀 개인메일로 보내시면 될듯용. 제 메일도 개인메일로..

**Comment by tirr-c** [comment]
보냈읍니다

**Comment by tirr-c** [comment]
80번 포트 열린 것 확인했습니다.

**Comment by simnalamburt** [comment]
열은 포트 목록. 모두 TCP 입니다.

- 21 (FTP)
- 22 (SSH)
- 23 (Telnet)
- 80 (http)
- 110 (pop3)
- 136 (PROFILE Naming System)
- 143 (imap)
- 1023
- 1999 (cisco identification port/subseven backd)
- 2000 (Senna trojan)
- 2556 (nicetec-nmsvc)
- 3001 (Phatbot worm)
- 3140 (Arilia Multiplexor)
- 3176 (ARS Master)
- 3306 (MySQL)
- 3389 (Windows Terminal)
- 3456 (Terror trojan)
- 4665 (Container Client Message Service)
- 5325 (Unassigned)
- 5400 (Blade Runner windows trojan)
- 5401 (Blade Runner windows trojan)
- 5402 (Blade Runner windows trojan)
- 5522 (Unassigned)
- 5800 (VNC)
- 5900 (VNC)
- 6257 (Unassigned)
- 6346 (gnutella-svc)
- 6699 (Unassigned)
- 9100 (HP Print jetdirect)

이 포트들은 학교에 서버를 놓을시 자동으로 막히는 포트의 전체 목록입니다. 제가 너무 짜증나서 막히는 모든 포트 목록을 요청했고, 전부 열어달라고 하니 전부 열어주더군요.

**포트의 사용기간은 1년이라서 매년 재신청해야합니다. 주의요망**

**Comment by simnalamburt** [comment]
### 포트 개방하는법
<esjee@cse.snu.ac.kr>로 메일보내면 됨. 바로 처리될때도 있는데, 신규 IP를 개방하는경우 우리가 중전으로 뭔가 메일을 다시 보내야 하는경우가 있는것같으니 주의. 요청할때엔 아래 항목이 모두 담기게 해야한다.

- IP (ex: 147.46.113.114)
- 도메인 (ex: uriel.upnl.org)
- 용도 (ex: 동아리 실습서버 및 동아리 홈페이지)
- 학외개방이 필요한 포트 목록 (https://github.com/upnl/work/issues/6#issuecomment-274075783 참고)

우리가 지쌤에게 요청을 드리면, 지쌤이 우리 대신 중전과 연락하여 포트를 열어주신다. 그 과정은 **[첨부파일](https://github.com/upnl/work/files/849407/default.zip)** 참고.

### 포트 개방해야하는 서버 목록
아래의 세 서버 포트를 주기적으로 열어줘야한다.

- [x] sodrak.upnl.org &rarr; 2017-10-26 까지 열려있음
- [x] uriel.upnl.org &rarr; 2018-01-13 까지 열려있음
- [x] edhelbroy.upnl.org &rarr; 2018-03-17 까지 열려있음

**Comment by simnalamburt** [comment]
소드락 만료기한이 넘어서 메일을 다시 보내야합니다.

@LiverselleR @tirr-c 지은상 선생님께 메일을 보내주세요. 이번에는 sodrak, uriel, edhelbroy 세 서버 모두 동시에 신청해주세요.

**Comment by simnalamburt** [comment]
자동연장 된다고 한다.

```
16:46 <티르> 그
16:46 <티르> 지은상쌤이 별 얘기 없으면 자동연장이라고 하셨어요
```

(2018-02-18)

**Comment by simnalamburt** [comment]
@tirr-c @pbzweihander 유리엘, 소드락, 에델브로이 세 서버에 대해 443번 포트를 개방해주세요.

http://uriel.upnl.org
http://sodrak.upnl.org

제가 지난번에 했을 때엔, 이렇게 별 기능 없는 소개페이지를 띄우기 위함이라고 안내해드리면 포트를 열어주셨었어요.

**Comment by simnalamburt** [comment]
여러번 재촉하자 언제인지는 모르겠으나 포트가 개방되었다. 기한 없이 상시 열리게되나, 정보화본부에서 임의로 닫을 수 있다. Closing
