### ISSUE TITLE
오래된 백업 적절하게 처리하기

### ISSUE THREAD

**Issue by tirr-c** [upnl/work#64]
S3에 쌓이는 백업이 만드는 비용이 5달러/월/월의 속도로 증가하고 있습니다.

오래된 백업을
- 지운다
- Glacier로 옮긴다

라이프사이클 훅으로 잘 해볼 수 있을 텐데 확인해봐야 합니다.

**Comment by simnalamburt** [comment]
https://github.com/upnl/infra/blob/7446a893c27de4200f077dabd03d7ec6853beb51/s3.tf#L4-L18

저거 주석 해제하고 어플라이하면 되긴 한데, 저런 규칙을 쓰면 문제가 있더라구여. 자동백업이 동작 안하거나 고장난걸 눈치 못챘을때에 모든 백업이 다 글레이시어로 가버려서 쓰지 못하는 경우가 발생했었어요.

"14일 지난 백업은 글레이시어로 보내되, 가장 최근 백업 5개는 무조건 S3에 유지" 이런 규칙을 만들고싶은데 어떻게 하면 좋을까여

**Comment by simnalamburt** [comment]
그런거 지원 안하는거같네요 걍 저거 주석 해제해야할거같아요

**Comment by simnalamburt** [comment]
적용 완료됨 https://github.com/upnl/infra/pull/8#issuecomment-656858220
