### ISSUE TITLE
Docker Hub 정리하기

### ISSUE THREAD

**Issue by simnalamburt** [upnl/work#65]
아래는 슬랙에서 내가 보낸 메시지

> @tirr-c @pbzweihander @Integraldx 여러분 안녕하세요. 이메일이나 트위터 등으로 들으셨겠지만, Docker Hub이 사업 접을라나본지, 6개월동안 활동이 없는 리포지터리는 모두 날려버리기로 결정했습니다.이에 따라 원래 도커헙에 있던 https://hub.docker.com/repository/docker/upnl/upnl-org-backup 이 리포를
GitHub에서 새로 개장한 https://github.com/orgs/upnl/packages/container/upnl-org-backup 로 옮겼습니다
>
> ```bash
> docker pull ghcr.io/upnl/upnl-org-backup
> ```
>
> 별도 세팅 없이 도커헙처럼 편하게 쓸 수 있습니다.문제는 기존에 `upnl/upnl-org-backup` 주소를 써서 돌던 yaml파일같은것들 경로를 `ghcr.io/upnl/upnl-org-backup` 로 바꾸는 작업이 남았다는건데, 세분중 한분꼐서 처리해주시면 증말 감사드리겠습니다

### TODOs
- [x] 기존에 `upnl/upnl-org-backup` 쓰던것 `ghcr.io/upnl/upnl-org-backup`로 바꾸기
- [x] [유피넬에서 쓰던 Docker Hub organization](https://hub.docker.com/orgs/upnl) 완전히 삭제하기

**Comment by pbzweihander** [comment]
https://github.com/orgs/upnl/packages/container/upnl-org-backup 링크가 404 Not Found가 뜨고, upnl org나 upnl-org-backup 리포의 패키지에서도 못 찾았는데 확인해주실 수 있나요?

**Comment by pbzweihander** [comment]
그리고 upnl-org-backup은 구 제미니에서 홈페이지가 서빙될 때 사용하던 백업툴이고 현재는 사용되지 않습니다.

지금 백업 스크립트는 kubernetes CronJob으로 직접 정의되어있습니다. (https://github.com/upnl/kubernetes/blob/master/service/homepage.yml#L191-L281)

**Comment by simnalamburt** [comment]
> https://github.com/orgs/upnl/packages/container/upnl-org-backup 링크가 404 Not Found가 뜨고, upnl org나 upnl-org-backup 리포의 패키지에서도 못 찾았는데 확인해주실 수 있나요?

패키지가 pull은 가능한데 들어가서 관리하는건 권한을 부여해야하네요. 권한을 드렸어요

**Comment by simnalamburt** [comment]
Docker Hub Org deactivate 했습니다

**Comment by simnalamburt** [comment]
upnl-org-backup 더 안쓴다니 archive처리하겠습니다
